-- Tabla para registrar todas las consultas ejecutadas
CREATE TABLE QUERY_LOG (
    LOG_ID VARCHAR2(32) PRIMARY KEY,
    QUERY_TYPE VARCHAR2(20) NOT NULL,  -- 'QUERY', 'EXEC', 'PROCEDURE'
    QUERY_TEXT CLOB NOT NULL,
    PARAMS CLOB,
    EXECUTION_TIME TIMESTAMP NOT NULL,
    DURATION VARCHAR2(50),
    ROWS_AFFECTED NUMBER,
    SUCCESS NUMBER(1) DEFAULT 1,
    ERROR_MSG CLOB,
    USER_IP VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para búsquedas rápidas
CREATE INDEX IDX_QUERY_LOG_TYPE ON QUERY_LOG(QUERY_TYPE);
CREATE INDEX IDX_QUERY_LOG_TIME ON QUERY_LOG(EXECUTION_TIME);
CREATE INDEX IDX_QUERY_LOG_SUCCESS ON QUERY_LOG(SUCCESS);
CREATE INDEX IDX_QUERY_LOG_CREATED ON QUERY_LOG(CREATED_AT);

-- Comentarios para documentación
COMMENT ON TABLE QUERY_LOG IS 'Registro de todas las consultas ejecutadas en la API';
COMMENT ON COLUMN QUERY_LOG.LOG_ID IS 'ID único del log';
COMMENT ON COLUMN QUERY_LOG.QUERY_TYPE IS 'Tipo de operación: QUERY, EXEC, PROCEDURE';
COMMENT ON COLUMN QUERY_LOG.QUERY_TEXT IS 'Texto de la consulta o nombre del procedimiento';
COMMENT ON COLUMN QUERY_LOG.PARAMS IS 'Parámetros de la consulta en formato JSON';
COMMENT ON COLUMN QUERY_LOG.EXECUTION_TIME IS 'Momento de ejecución';
COMMENT ON COLUMN QUERY_LOG.DURATION IS 'Duración de la ejecución';
COMMENT ON COLUMN QUERY_LOG.ROWS_AFFECTED IS 'Número de filas afectadas';
COMMENT ON COLUMN QUERY_LOG.SUCCESS IS '1 = éxito, 0 = error';
COMMENT ON COLUMN QUERY_LOG.ERROR_MSG IS 'Mensaje de error si falló';
